travis2docker/travis2docker.py
Testing in my local before of merge
=> [FIX] environment variables

.travis.yml, travis2docker/travis2docker.py
=> [IMP] travis2docker: Enable TRAVIS_REPO_SLUG environment variable for travis

travis2docker/travis2docker.py
- Fix http://stackoverflow.com/questions/3411048/unexpected-operator-in-shell-programming
=> [FIX] travis2docker: Fix unexpected-operator

travis2docker/travis2docker.py
Fix unexpected-operator http://stackoverflow.com/questions/3411048/unexpected-operator-in-shell-programming
=> [FIX] travis2docker: Fix unexpected-operator part 2

travis2docker/travis2docker.py
Hi Friends!
Thanks for the excellent app, it has really helped us integrate our existing CI into the Odoo testing workflow. 
We did have to add a few CLI args to make it work for our purposes; figured you may want them as well:
* `--remove-after-success` - Hard codes a removal of the `after_success` section - we use in-house coverage solution, so needed this to be explicitly removed to keep from coveralls from generating errors
* `--include-cleanup` - Injects image removal into Docker run script in order to save space
* `--no-cache` - Injects `--no-cache` into Docker build script in order to eliminate stale builds
I basically learned Docker with this project, so if you have a better solution to something I did here, I'm all ears :smile:
=> Add no-cache, include-cleanup, and remove-after-success CLI args

travis2docker/travis2docker.py
=> [FIX] travis2docker: Fix Vauxoo/travis2docker#36 - avoid run after_succes section

travis2docker/travis2docker.py
- To add compatibility with use hard-coded of this remote name
=> [REF] travis2docker: Save origin remote

travis2docker/travis2docker.py
- Change the owner just in items that really required.
=> [IMP] travis2docker: Improvement performance in chown command

src/travis2docker/cli.py
- Add supports for `travisfile2dockerfile --version`
- Fix https://github.com/Vauxoo/travis2docker/issues/23
=> [REF] Add version argument

src/travis2docker/templates/Dockerfile, tests/test_travis2docker.py, tox.ini
[IMP] Check invalid Dockerfiles from tests
=> [FIX] template Dockerfile: Fix newline syntax error

examples/example_4.yml, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
=> [IMP] Support .travis.yml with matrix key without env key

.gitmodules, MANIFEST.in, examples/example_1.yml, examples/example_4.yml, src/travis2docker/templates/Dockerfile, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
=> [IMP] Support apt-sources and apt-packages of .travis.yml.

src/travis2docker/templates/Dockerfile
Fix https://github.com/Vauxoo/maintainer-quality-tools/issues/136
=> [REF] Dockerfile: Use original path like as travis, 'build' folder.

src/travis2docker/templates/Dockerfile, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
- Finish TODO comments
- Use of join method in string from jinja template
- Adjust test for new changes
=> [REF] global refactoring: Support before install and add bin bash to script files

src/travis2docker/templates/Dockerfile, src/travis2docker/templates/entrypoint.sh, src/travis2docker/templates/rvm_env.sh, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
As noted in Vauxoo/docker-odoo-image#165
* Add bash encapsulation & sourcing for install commands
* Add RVM source to entrypoint
=> [ADD] Dockerfile: Support for RVM

src/travis2docker/cli.py, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
You will can run: `... --add-rcfile="~/.pylintrc,~/.other_rc_file"...` in order to enable custom configuration local files to container
=> [IMP] travis2docker: Support copy rcfiles

src/travis2docker/git_run.py, src/travis2docker/templates/Dockerfile, src/travis2docker/travis2docker.py
=> [REF] Template: Fix detection of pull request and clean comments

src/travis2docker/travis2docker.py
=> [ADD] Adding sleep 2 to file script file fixed #86

src/travis2docker/templates/Dockerfile
Following good practices about
=> [REF] t2d: Use COPY instead of ADD

src/travis2docker/cli.py, src/travis2docker/git_run.py, src/travis2docker/templates/Dockerfile
Fix https://github.com/Vauxoo/runbot-addons/issues/92
To reproduce the error
```bash
travisfile2dockerfile --add-remote=vauxoo,vauxoo-dev git@gitlab.com:Group/repo.git master
```
=> [FIX] travis2docker: Fix --remotes parameter not support gitlab or other domain

src/travis2docker/cli.py
Continuation of https://github.com/Vauxoo/travis2docker/pull/94
=> [REF] travis2docker: Default user for common images (cli)

README.rst
don't -> doesn't, use -> uses, etcc
=> [REF] README: Fix syntax

src/travis2docker/templates/Dockerfile, src/travis2docker/templates/entrypoint.sh, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
- [REF] copy_path: Skip copy errors
=> [IMP] templates: Using virtualenv for each odoo version to faster installation

.travis.yml, setup.cfg, src/travis2docker/cli.py, src/travis2docker/travis2docker.py, tox.ini
Allow run custom scripts for script file.
=> [REF] travis2docker: Add parameter runs_at_the_end_script

src/travis2docker/cli.py, src/travis2docker/templates/Dockerfile, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
More info about: https://vsupalov.com/docker-build-time-env-values
=> [IMP] travis2docker: Supports for build environment variable args

src/travis2docker/travis2docker.py
https://docs.travis-ci.com/user/build-stages/
=> [IMP] travis2docker: Support jobs

.travis.yml, requirements.txt, tox.ini
Fix https://github.com/Vauxoo/travis2docker/issues/138
=> [FIX] requirements: Compatibility with >=py3.10

src/travis2docker/cli.py, src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/build.sh, src/travis2docker/templates/entrypoint_deployv.sh, src/travis2docker/travis2docker.py
Allow run your travis2docker command with `--deployv` compatibility
=> [IMP] t2d: Compatible with deployv images

src/travis2docker/docker_helper/build.py, src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/build.sh, src/travis2docker/travis2docker.py
Set dev remote
Set fetch compatibility
Set ssh private url remote
=> [IMP] travis2docker: deployv - Set remotes

src/travis2docker/cli.py, src/travis2docker/travis2docker.py
New version of vxci allows us to use sha as tag:
Related to https://git.vauxoo.com/devops/vxci/-/merge_requests/17
=> [REF] travis2docker: Supporting new tag using sha to get the tag name in a static way

src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/build.sh
Fixes #165 
`--build-extra-args` was mentioned on #164, however looking trough code I also saw `--build-env-args` which is already being used in code and Dockerfile templates, so I went with that.
=> [IMP] t2d: Optional VIM install through --build-env-args #165

src/travis2docker/templates/build.sh
Fixes all the points listed on the review on #176. 
Marked as draft since some fixes are still missing and I am yet to build a full image and test vim out.
=> [FIX] t2d: Vim installation now working

src/travis2docker/templates/build.sh
Related to https://github.com/Vauxoo/travis2docker/issues/165#issuecomment-1292940101
=> [REF] vim-spf13: deployv - Improve message

.github/workflows/github-actions.yml, src/travis2docker/cli.py
=> [FIX] Updated help string of --root-path to reflect the correct default value

src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/build.sh
New Orchest docker image have a new entrypoint script
Now it is called in order to set configuration file values
=> [REF] build: Use new entrypoint script
