Vauxoo/travis2docker

travis2docker/travis2docker.py
- Using a list of len equal to one
because global section is manage one_global*each_matrix in travis
=> [FIX] travis2docker: Fix global section.

travis2docker/test/main.py, travis2docker/travis2docker.py
@moylop260 
Sorry when I switched to the new command, I flipped the str formatting around and put the build args when the tag should have been - resulting in an error. 
I fixed it, and added a test (because I should have done that anyways)
=> Fix build args ordering and add bug test

travis2docker/travis2docker.py
- When you run `docker build ...` generate intermediate containers that are removed if there isn't errors, but if there are errors then the container aren't removed.
- The param `docker build --rm ..` force delete the intermediate containers.
=> [REF] travis2docker: Add build rm default

travis2docker/travis2docker.py
This change adds public ssh key as authorized keys including `id_rsa.pub` key.
This is handy for `ssh` (of course) and when using `mosh`
Thanks @hbto for the hint
Demo:
[![](https://asciinema.org/a/0n09jwlglh0hkhxgqme79arza.png)](https://asciinema.org/a/0n09jwlglh0hkhxgqme79arza)
=> [IMP] Add authorized_keys

travis2docker/travis2docker.py
Fix case when a `.travis.yml` use 
```yml
after_success:
```
=> [FIX] travis2docker: Fix when a yml tag is empty and get None value.

src/travis2docker/templates/Dockerfile, src/travis2docker/templates/entrypoint.sh
The image of travis for python use a virtual environment and a pre-installed npm
=> [IMP] templates: Support quay.io/travisci/travis-python image

src/travis2docker/travis2docker.py
Avoid a assign from class instead of a assign from obj
```python
class MyClass(object):
my_var = None
def __init__(self):
self.my_var2 = None
MyClass.my_var = 2
obj1 = MyClass()
print obj1.my_var  # show value 2
```
=> [REF] travis2docker: Clean variable from OOP

.travis.yml, src/travis2docker/templates/Dockerfile, src/travis2docker/templates/entrypoint.sh, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
With this change now the `travis2docker` can be support many version of python 
The list of version of python are :
```
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- 3.6
```
Now for each version inside the `.travis.yml` travis2docker creates a folder with the number of the python version
For example if I made o travis2docker over the follow repository git@github.com:vauxoo-dev/asdcust.git using the branch 10.0-two-version
```
Script generated: 
/tmp/travis2docker/script/git_github.com_vauxoo-dev_asdcust.git/10.0-two-version/2_7/1
/tmp/travis2docker/script/git_github.com_vauxoo-dev_asdcust.git/10.0-two-version/2_7/2
/tmp/travis2docker/script/git_github.com_vauxoo-dev_asdcust.git/10.0-two-version/3_5/1
/tmp/travis2docker/script/git_github.com_vauxoo-dev_asdcust.git/10.0-two-version/3_5/2
```
And the …
=> [IMP] travis2docker: Adding the possibility to support many version of python

src/travis2docker/templates/Dockerfile, src/travis2docker/templates/entrypoint.sh
Only use the name of the `python` version not use the sub fix `_with_system_site_packages`
To avoid additional  validation when the `travis` imagen is used
=> [FIX] travis2docker: Fix the name of the python version in travis image

src/travis2docker/templates/Dockerfile
With this change when the user made ssh login over the container the file `/etc/environment` load the correct version of python
Fix https://github.com/Vauxoo/travis2docker/issues/108
=> [FIX] entrypoin.sh: Fix the python version when the user made ssh login using the file /etc/environment

src/travis2docker/templates/Dockerfile, src/travis2docker/templates/entrypoint.sh, tests/test_travis2docker.py
This reverts PR https://github.com/Vauxoo/travis2docker/pull/111
This reverts PR https://github.com/Vauxoo/travis2docker/pull/112
This reverts commit 1bf31d2dff086a4b8b57cd405af344238e62edb1.
This reverts commit f39fb717b5f3ce48f8c80b5f0b0fec2fcc86656e.
This reverts commit b14ca3db21786ea1464bc1db525932219b8f86b3.
There are too many tests to do before releasing this logic,
runbot_travis2docker tests failing with the new base image and new t2d
release.
=> Revert "[IMP] templates: Using virtualenv for each odoo version to faster installation"

src/travis2docker/travis2docker.py
Because default base image are not installed all minor versions of python
=> [REF] travis2docker: Just use main python version

examples/example_5.yml, src/travis2docker/travis2docker.py, tests/test_travis2docker.py
This change adds support for the key `addons` -> `postgresql`, located
in the file `.travis.yml`. That key is used to manually specify the
PostgreSQL version, instead of using the default one.
For more information, see:
https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version
Closes #116
=> [IMP] travis2docker: Add support for key to specify PostgreSQL version

.travis.yml, requirements.txt, tox.ini
- [REF] tox.ini: Fix false red using git-submodules
=> [REF] requirements.txt: Using valid pyyaml and jinja versions for py2 and py3

src/travis2docker/__main__.py, src/travis2docker/cli.py, tests/test_travis2docker.py
The program's exit code was being taken from the list that contains the
created scripts. When `os.exit` gets a parameter different from `None` and
an integer, the parameter is printed and the exit status will be one (i.e.
failure).
This was structured that way to be able to print created scripts when called
from `__main__`.
To solve the above, resulting scripts are always printed and no arguments are
passed as exit code.
In addition, printer result is prettier now, it's as follows::
```
Generated scripts:
- script_1
- script_2
```
Closes #99
=> [FIX] travis2docker: Always exit with a failure code

src/travis2docker/travis2docker.py
When the Python version is not specified globally on the `.travis.yml`
file (i.e. using the `python`key), no scripts were generated.
Closes #129
=> [FIX] travis2docker: Generate scripts when global version is not set

src/travis2docker/travis2docker.py
deployv is using main_app as tag in the docker images
=> [REF] travis2docker: Using main_app as image's tag instead of customer

src/travis2docker/templates/build.sh
pdbpp is used by dev team
ifconfig & iproute2 are network tools used frequently
multitail is showing the terminal in red color
=> [REF] travis2docker: Install pdbpp, ifconfig & iproute2 and remove multitail

src/travis2docker/templates/Dockerfile_deployv, tox.ini
Related to https://askubuntu.com/a/1415153
=> [FIX] travis2docker: deployv dockerfile - Use venv/bin/activate instead of venv/local/activate set DEB_PYTHON_INSTALL_LAYOUT=deb

src/travis2docker/templates/build.sh
PR adds missing dependency `libecpg-dev` to fix the error: 
`Unable to execute 'ecpg', you likely need to install it.' - 'apt install -y libecpg-dev
`
=> [FIX] travis2docker: add missing dependency libecpg-dev

src/travis2docker/templates/build.sh
Runbot and local dev envs have resources limited
And MQT was using workers=0
We need to match as possible in order to avoid variations when errors
=> [REF] travis2docker: deployv - Disable workers

src/travis2docker/docker_helper/build.py
if org is stable so add dev if org is dev so add 'stb'
If the remote is using org "Vauxoo" so a extra remote is added for "vauxoo-dev"
If the remote is using org "Vauxoo-dev" so a extra remote is added for "vauxoo"
=> [FIX] travis2docker: deployv - Fix extra remote

src/travis2docker/templates/.vscode/extensions.json, src/travis2docker/templates/.vscode/launch.json, src/travis2docker/templates/.vscode/settings.json, src/travis2docker/travis2docker.py
A `.vscode` folder is copied onto the container, this autoconfigures some things:
- Odoo imports are resolved (you can Ctrl+Click on them and go to the source code), also autocompletes Odoo methods
- Useful extensions are suggested, upon opening Vscode should give users the option to install all recommended exceptions.
- A `launch.json` is included, this lets you run and debug Odoo in different modes with the click of a button. Right now only "Odoo" and "Odoo Tests" modes are included.
I mark this as draft since there are some things to consider before committing:
1. Since this is a dev instance I am not sure there should be an Odoo service. Especially since it is more convenient to launch and stop it trough Vscode. Right now when launching from Vscode the port is already in use so that …
=> [IMP] Include .vscode for autoconfiguration

src/travis2docker/cli.py
Fixes #167 
Root path is set to `$HOME/t2d`, I also took the liberty to create an extra folder per repo. So for example if I clone `vauxoo/random` all files created by t2d will be stored on `$HOME/t2d/vauxoo__random`, I think that is the expected behavior when someone hears root path, and the only way a default would be useful, otherwise I would still need to tell t2d where to store this specific project (relative to root path).
=> [IMP] t2d: Default --root-path #167

src/travis2docker/templates/build.sh
Fixes #164 
Also removed `cp /root/.zshrc /home/odoo/.zshrc` which was not necessary and was failing during docker build.
=> [IMP] t2d: Use ZSH_INSTALL to enable ZSH installation

tests/test_travis2docker.py, tox.ini
The branch `master` was renamed to `main` so all unit tests were failing. This fixes them.
=> [FIX] t2d: Branch name for testing updated to main

src/travis2docker/templates/build.sh
The following error:
```
[odoo@e1f6a53af9ef]~/instance/extra_addons/account-customer-invoice-split-discount/account_customer_invoice_split_discount/models$
(14.0)$ vim account_move.py
Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.
Press ENTER or type command to continue
```
Is now fixed.
Also removed unknown `-d` flag when using `git clone`. Hint message when skipping vim autoconfiguration was improved too.
=> [FIX] t2d: Taglist plugin for vim now loaded I#165

src/travis2docker/templates/.coveragerc, src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/build.sh, src/travis2docker/travis2docker.py
Fixes #178 
Coverage reports are automatically generated with the new inbuilt command `vxcov`.
=> Draft [IMP] t2d: Automatically run odoo tests and generate coverage reports

src/travis2docker/templates/build.sh
YouCompleteMe was causing issues as ycmd was not being installed properly, however installating it offers no benefit since it did not mention support for python3 autocompleting, and it is not used for the pdb + TAB -> `__import__('pdb').set_trace()` feature which is the most requested feature by Vauxoo Devs. Therefore it was removed.
=> [FIX] t2d: Remove vim YouCompleteMe plugin I#165

src/travis2docker/cli.py, src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/build.sh
Fixes #186
`/home/odoo/.cache` is created when installing vim by the `ctrlp` vim plugin and is owned by root. This causes issues when other programs like pre-commit are run without privileges by end users and try to access `.cache`.
=> [FIX] t2d: Permission issues on ~/.cache (#186)

.github/workflows/github-actions.yml, CONTRIBUTING.rst, src/travis2docker/templates/entrypoint_deployv.sh, tests/test_travis2docker.py, tox.ini
EXCLUDE was not being taken into account when deciding which modules to install and run when using --deployv. Fixed the entrypoint to do so
=> FIX: CI and consider EXCLUDE env var in deployv entrypoint

.github/workflows/github-actions.yml
Previous refactoring in the matrix syntax for github-actions.yml caused a regression where packages were no longer being built and new versions were not being automatically published to pypi.
This commit fixes the 'if' conditions so packages are built and published once again.
=> Fix: Github Actions not publishing releases

src/travis2docker/cli.py
Fixes #188.
Usage of travis.yml to create docker containers is being deprecated in favor
of directly creating containers from their deployv image, this can be
manually enabled with the "--deployv" flag.
Since travis.yml is no longer used, some repos are deleting it, this
caused errors since t2d expects it to exist.
This commit makes it possible for t2d to work with repositories that
have no travis.yml file. t2d will automatically fallback and enable
the --deployv flag whenever no "travis.yml" file is found and
the file "variables.sh" exists.
=> Fallback to --deployv when travis.yml is not found and variables.sh exists

src/travis2docker/cli.py, src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/build.sh
Fixes #193
The container automatically copies the user's public key to its authorized_keys, allowing users to connect via SSH.
id_rsa.pub was the default key the Dockerfile looked for, since it is deprecated (in favor of ed25519) a new script (function) "set_authorized_keys" was added.
This script:
1. Tries to first copy id_ed25519.pub (if it exists)
2. If it does not, it falls back to RSA keys and prints a deprecation warning (if it exists).
3. Otherwise it alerts the user to the fact nothing was copied.
Also, since the condition add_self_rsa_pub was hardcoded to True, it was removed and the keys are just copied directly.
=> [IMP] Add support for ed25519 keys and prefer them over RSA

.github/workflows/github-actions.yml, setup.py, tox.ini
* Test the package can be build without errors
* Test the bump2version script
* Add missing long description format: rst
* CI uses tox -e build
Based on pylint-odoo project
=> [REF] tox: Add new env "build" to test the package build

src/travis2docker/templates/10-build.sh
In order to have a better user experience, we must ensure that the latest image is always used, therefore the argument --pull has been added
=> [IMP] pull image before building

src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/entrypoint_deployv.sh
Fixes #200.
When supplying t2d the "START_SSH" argument during setup it is expected
that the generated image will automatically start running  the ssh
service.
This was not happening when using --deployv, it has been fixed by
adding the logic to autostart the server in the entrypoint for it.
Since the SSH server can only be started by root, the other commands
in the entrypoint have been modified to use the correct user if the
image is being run as root.
The same support has been given to ODOO and PSQL services. They start by
default but this can be avoided by providing a falsy value for
START_ODOO and START_PSQL respectively.
=> [FIX] start ssh server when `START_SSH` build-env-arg is supplied (deployv)

src/travis2docker/templates/Dockerfile_deployv, src/travis2docker/templates/build.sh, src/travis2docker/travis2docker.py
Since /home/odoo/.ssh is marked as a volume in the parent image, changes to files in the directory during docker build are being lost when a new container is created. Therefore the authorized_keys file is set directly on the host and copied over to the container.
Closes #211.
=> [FIX] t2d: add ssh key to authorized_keys

.github/workflows/github-actions.yml, requirements-dev.txt, setup.py, tox.ini
* Exclude MacOSX-latest for py old
* Add py3.12 setup compatible
* Add separated cache for MacOSX M1
* Fix build
=> [REF] github-actions: Use exclude macosx-latest for py old, add py3.12, MacOSX M1 cache and fix build

src/travis2docker/templates/build.sh
It is useful for environment variable enabled PIP_BREAK_SYSTEM_PACKAGES
Fix the following error
```txt
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.11/README.venv for more information.
note: If …
```
=> [FIX] build.sh: Use the same environment variables for sudo commands

src/travis2docker/templates/build.sh
Similar to https://git.vauxoo.com/vauxoo/docker-postgresql/-/merge_requests/43
t2d is using the same odoo image installing psql in order to be compatible with the current runbot
So, we need to install the same package for the psql docker image
TODO: Migrate to use the psql docker image instead in the future (not priority today)
=> WIP: [REF] build.sh: Install pg_vector dependencies

src/travis2docker/templates/Dockerfile_deployv
New docker image missing files than old version
=> [FIX] Dockerfile_deployv: Protect mv files only if exists

src/travis2docker/travis2docker.py
When granting access to SSH keys by adding the same public key to the `authorized_keys` file, the existing file was being overwritten, because the mode "w" was being used instead of "a". This is the equivalent of using `>` instead of `>>` in shell.
To solve this, the "a" mode is now used.
=> [FIX] travis2docker: don't overwrite existing keys
